// <auto-generated />
using System;
using Invoice_Gen.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoice_Gen.Domain.Migrations
{
    [DbContext(typeof(InvoiceGenDbContext))]
    [Migration("20230626213853_AddedLineItemsTable")]
    partial class AddedLineItemsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Invoice_Gen.Domain.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ClientId");

                    b.ToTable("Clients", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = 1,
                            ClientAddress = "4509 Clement Street, Atlanta, GA 30331",
                            ClientName = "Muller Inc",
                            ContactEmail = "AaronDBaker@dayrep.com",
                            ContactName = "Bradley S Crooks"
                        },
                        new
                        {
                            ClientId = 2,
                            ClientAddress = "2545 James Street, Fairport, NY 14450",
                            ClientName = "Gutkowski Inc",
                            ContactEmail = "AnnaLWitt@teleworm.us",
                            ContactName = "Anna L. Witt"
                        },
                        new
                        {
                            ClientId = 3,
                            ClientAddress = "923 Euclid Avenue, San Luis Obispo, CA 93401",
                            ClientName = "Hoeger - Gislason",
                            ContactEmail = "SusanMRailey@armyspy.com",
                            ContactName = "Susan Railey"
                        },
                        new
                        {
                            ClientId = 4,
                            ClientAddress = "2607 Goldcliff Circle, Washington, DC 20005",
                            ClientName = "Toy Group",
                            ContactEmail = "StanleyDRogers@dayrep.com",
                            ContactName = "Stanley D. Rogers"
                        },
                        new
                        {
                            ClientId = 5,
                            ClientAddress = "1381 Monroe Street, Houston, TX 77030",
                            ClientName = "Upton, Gleason and Cronin",
                            ContactEmail = "TammyWFinley@dayrep.com",
                            ContactName = "Tammy W. Finley"
                        });
                });

            modelBuilder.Entity("Invoice_Gen.Domain.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("VatRate")
                        .HasColumnType("INTEGER");

                    b.HasKey("InvoiceId");

                    b.HasIndex("ClientId");

                    b.ToTable("Invoices", (string)null);

                    b.HasData(
                        new
                        {
                            InvoiceId = 1,
                            ClientId = 1,
                            DueDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            VatRate = 25
                        });
                });

            modelBuilder.Entity("Invoice_Gen.Domain.Models.LineItem", b =>
                {
                    b.Property<int>("LineItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Cost")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("LineItemId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("LineItems", (string)null);

                    b.HasData(
                        new
                        {
                            LineItemId = 1,
                            Cost = 80.0,
                            Description = "Time spent building API (per hour)",
                            InvoiceId = 1,
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("Invoice_Gen.Domain.Models.Invoice", b =>
                {
                    b.HasOne("Invoice_Gen.Domain.Models.Client", "Client")
                        .WithMany("Invoices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Invoice_Gen.Domain.Models.LineItem", b =>
                {
                    b.HasOne("Invoice_Gen.Domain.Models.Invoice", "Invoice")
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Invoice_Gen.Domain.Models.Client", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("Invoice_Gen.Domain.Models.Invoice", b =>
                {
                    b.Navigation("LineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
